services:
  - type: web
    name: eurydice-web
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn Eurydice.wsgi

    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "eurydice-web.onrender.com,.onrender.com,localhost"
      - key: DATABASE_URL
        value: "PASTE_YOUR_REAL_NEON_DATABASE_URL_HERE"
      - key: CLOUDINARY_URL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

    autoDeploy: true

    postdeploy:
      - python manage.py migrate --noinput
      - |
          python manage.py createsuperuser \
          --noinput \
          --username "$DJANGO_SUPERUSER_USERNAME" \
          --email "$DJANGO_SUPERUSER_EMAIL" || true
      - |
          python manage.py shell -c "
from django.contrib.auth import get_user_model
User = get_user_model()
u = User.objects.get(username='$DJANGO_SUPERUSER_USERNAME')
u.set_password('$DJANGO_SUPERUSER_PASSWORD')
u.save()
print('Superuser password set successfully.')
"
