services:
  - type: web
    name: eurydice-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn Eurydice.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "eurydice-web.onrender.com"
      - key: CLOUDINARY_URL
        sync: false
    autoDeploy: true
